local function title()
	local height = love.graphics.getHeight() / _G.Y_SCALE
	local width = love.graphics.getWidth() / _G.X_SCALE
	love.graphics.setFont(GameFont)
	love.graphics.setColor(0.5, 1, 1)
	love.graphics.rectangle("fill", 0, 0, width, height)
	love.graphics.setColor(0, 0, 0)
	love.graphics.print("Tanks-A-Lot", 100, 100)
end

function DrawMenu()
	local bwidth, bheight = 300 * _G.X_SCALE, 140 * _G.Y_SCALE
	title()
	GUI:newButton(100, 200, bwidth, bheight, "Play", MENU_POS == 0 and true or false)
	GUI:newButton(100, 350, bwidth, bheight, "???", MENU_POS == 1 and true or false)
	GUI:newButton(100, 500, bwidth, bheight, "???", MENU_POS == 2 and true or false)
	GUI:newButton(100, 650, bwidth, bheight, "Quit", MENU_POS == 3 and true or false)

	love.graphics.setColor(255, 255, 255) -- reset colours
end
