function DrawPause()
	local opacity = 0.3
	local height = love.graphics.getHeight()
	local width = love.graphics.getWidth()
	local bwidth, bheight = 300, 140
	love.graphics.setFont(GameFont)

	DrawGame() --Draw a single frame of the game
	love.graphics.setColor(0.1, 0.1, 0.1, opacity) --overlay opaque img
	love.graphics.rectangle("fill", 0, 0, width, height)

	love.graphics.setColor(1, 1, 1)
	love.graphics.print("PAUSED", 100, 100)
	--love.graphics.print("" .. PAUSE_POS, 200,200)

	GUI:newButton(100, 200, bwidth, bheight, "Return", PAUSE_POS == 0 and true or false)
	GUI:newButton(100, 350, bwidth, bheight, "Menu", PAUSE_POS == 1 and true or false)
	GUI:newButton(100, 500, bwidth, bheight, "Quit", PAUSE_POS == 2 and true or false)

	love.graphics.setColor(255, 255, 255) -- reset colours
end
